/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.workshop;

import me.workshop.util.GCPPropertiesLoader;
import me.workshop.util.LocalPropertiesLoader;

public class App {
    static String propertiesFilePath = "/Users/satyaanumolu/POCs/gcp.properties";
    static String gcp_secret_props_name = "dev-props";
    public static void main(String[] cliArgs) {
//        LocalPropertiesLoader props = LocalPropertiesLoader.getInstance(propertiesFilePath);
//        System.out.println(props.getProperty("gcp_db_sql_instance_name"));

        GCPPropertiesLoader gcpProps = GCPPropertiesLoader.getInstance(gcp_secret_props_name);
        System.out.println(gcpProps.getProperty("gcp_db_sql_instance_name"));


    }
}
